"""corrected order of BookTag and Tag tables

Revision ID: da8b37ac8fac
Revises: 46f86eb87edc
Create Date: 2025-02-09 17:22:32.943053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'da8b37ac8fac'
down_revision: Union[str, None] = '46f86eb87edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
